# apiVersion: helm.crossplane.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: default
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   credentials:
#     source: InjectedIdentity