# apiVersion: kubernetes.crossplane.io/v1alpha1
# kind: ProviderConfig
# metadata:
#   name: kubernetes-provider
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   credentials:
#     source: InjectedIdentity