apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: vcluster-test
spec:
  forProvider:
    chart:
      name: vcluster
      repository: https://charts.loft.sh
      version: 0.14.0
    namespace: vcluster-test
    values:
      syncer:
        extraArgs:
        - --out-kube-config-secret=vcluster-kubeconfig
        - --out-kube-config-server=https://vcluster-test.vcluster-test.svc.cluster.local
        - --tls-san=vcluster-test.vcluster-test.svc.cluster.local
      sync:
        ingresses:
          enabled: true
        poddisruptionbudgets:
          enabled: true
  providerConfigRef:
    name: default