apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: crossplane
    path: crossplane
    repoURL: https://github.com/ilia-medvedev-codefresh/crossplane-training.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true